export const MAKE_DRAFT_START = 'MAKE_DRAFT_START';
export const MAKE_DRAFT_SUCCESS = 'MAKE_DRAFT_SUCCESS';
export const MAKE_DRAFT_FAILURE = 'MAKE_DRAFT_FAILURE';

export const SAVE_PHOTO_START = 'SAVE_PHOTO_START';
export const SAVE_PHOTO_SUCCESS = 'SAVE_PHOTO_SUCCESS';
export const SAVE_PHOTO_FAILURE = 'SAVE_PHOTO_FAILURE';

export const SAVE_PRODUCT_START = 'SAVE_PRODUCT_START';
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS';
export const SAVE_PRODUCT_FAILURE = 'SAVE_PRODUCT_FAILURE';

export const REMOVE_PHOTO_START = 'REMOVE_PHOTO_START';
export const REMOVE_PHOTO_SUCCESS = 'REMOVE_PHOTO_SUCCESS';
export const REMOVE_PHOTO_FAILURE = 'REMOVE_PHOTO_FAILURE';


