export const RECOVER_EMAIL_START = 'RECOVER_EMAIL_START';
export const RECOVER_EMAIL_SUCCESS = 'RECOVER_EMAIL_SUCCESS';
export const RECOVER_EMAIL_FAIL = 'RECOVER_EMAIL_FAIL';

export const RECOVER_OTP_START = 'RECOVER_OTP_START';
export const RECOVER_OTP_SUCCESS = 'RECOVER_OTP_SUCCESS';
export const RECOVER_OTP_FAIL = 'RECOVER_OTP_FAIL';

export const RECOVER_PASSWORD_START = 'RECOVER_PASSWORD_START';
export const RECOVER_PASSWORD_SUCCESS = 'RECOVER_PASSWORD_SUCCESS';
export const RECOVER_PASSWORD_FAIL = 'RECOVER_PASSWORD_FAIL';