export const GET_MY_PRODUCT_START = 'GET_MY_PRODUCT_START';
export const GET_MY_PRODUCT_SUCCESS = 'GET_MY_PRODUCT_SUCCESS';
export const GET_MY_PRODUCT_FAILURE = 'GET_MY_PRODUCT_FAILURE';


export const REMOVE_PRODUCT_START = 'REMOVE_PRODUCT_START';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT_FAILURE = 'REMOVE_PRODUCT_FAILURE';

