export const GET_PRODUCT_START = 'GET_PRODUCT_START';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

export const ADD_FAV_PRODUCT_START = 'ADD_FAV_PRODUCT_START'
export const REMOVE_FAV_PRODUCT_START = 'REMOVE_FAV_PRODUCT_START'

export const ADD_FAV_PRODUCT_SUCCESS = 'ADD_FAV_PRODUCT_SUCCESS'
export const REMOVE_FAV_PRODUCT_SUCCESS = 'REMOVE_FAV_PRODUCT_SUCCESS'

export const ADD_FAV_PRODUCT_FAIL = 'ADD_FAV_PRODUCT_FAIL'
export const REMOVE_FAV_PRODUCT_FAIL = 'REMOVE_FAV_PRODUCT_FAIL'